# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-06 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('col6', models.CharField(max_length=45)),
                ('col7', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
