# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-05 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('col1', models.CharField(max_length=45)),
                ('col2', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
