# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRestPermissionTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='col1',
            field=models.CharField(choices=[(b'bar', b'Bar'), (b'world', b'World')], max_length=45),
        ),
    ]
