# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-06 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRestPermissionTest', '0002_auto_20190506_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('col4', models.CharField(max_length=45)),
                ('col5', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRelationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('col3', models.CharField(max_length=45)),
                ('another_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoRestPermissionTest.AnotherTestModel')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoRestPermissionTest.TestModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
