# Generated by Django 2.2.3 on 2019-07-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_builder', '0007_auto_20190214_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterFieldExtendedModel',
            fields=[
                ('filterfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_builder.FilterField')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_builder_extended_filter_field_extended',
            },
            bases=('report_builder.filterfield', models.Model),
        ),
        migrations.CreateModel(
            name='ReportExtendedModel',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report_builder.Report')),
            ],
            options={
                'db_table': 'report_builder_extended_report_extended',
            },
            bases=('report_builder.report', models.Model),
        ),
    ]
