version: '3.3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'library'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: "redis:6.0.6-alpine"
    command: redis-server
    ports:
      - "6380:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  django:
    build:
      context: .
    working_dir: /home/ubuntu/library
    command: 'gunicorn library.wsgi:application --bind 0.0.0.0:8080'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    ports:
      - 8080:8080
    depends_on: 
      - mysql
      - redis


volumes:
  my-db: